siaa/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from siaa import views

urlpatterns = [
    path('', views.index, name='index'),
    path(r'admin/', admin.site.urls),
    path('autenticacion/', include('app.autenticacion.urls')),
    path('academico/', include('app.academico.urls')),
    path('cientifica/', include('app.cientifica.urls')),
    path('core/', include('app.core.urls')),
    path('hveterinario/', include('app.hveterinario.urls')),
    path('reporte/', include('app.reporte.urls')),
    path('organico/', include('app.organico.urls')),
    path('planificacion/', include('app.planificacion.urls')),
    path('seguridad/', include('app.seguridad.urls')),
    path('seguridad-informacion/', include('app.seguridad_informacion.urls')),
    path('talento-humano/', include('app.talento_humano.urls')),
    path('tesoreria/', include('app.tesoreria.urls')),

    # Url de api
    path('api/v1/bienes/', include('api.bienes.urls')),
    path('api/v1/configuracion/', include('api.configuracion.urls')),
    path('api/v1/core/', include('api.core.urls')),
    path('api/v1/curricular/', include('api.curricular.urls' )),
    path('api/v1/organico/', include('api.organico.urls')),
    path('api/v1/recaudacion/', include('api.recaudacion.urls')),
    path('api/v1/seguridad/', include('api.seguridad.urls')),
    path('api/v1/talento-humano/', include('api.talento_humano.urls')),

    #Url servicios externos
    path('api/v1/bsg/', include(('api.bsg.urls', 'api_bsg'))),
    path('api/v1/banco/', include(('api.banco.urls', 'api_banco'))),
    path('api/v1/eventos/', include(('api.eventos.urls', 'api_eventos'))),
    path('api/v1/google/', include(('api.google.urls', 'api_google'))),
    path('api/v1/ldap/', include(('api.ldap.urls', 'api_ldap'))),
    path('api/v1/sga/', include(('api.sga.urls', 'api_sga'))),
]

app/academico/models/curricular.py
from django.core.exceptions import ValidationError
from django.db import models

REGIMEN_2013 = "2013"
CHOICE_REGIMEN = ((REGIMEN_2013, "2013"),)

class Asignatura(models.Model):
    TIPO_CURSO_APOYO = "CURSO_APOYO"
    TIPO_PROGRAMA_ESTUDIO = "PROGRAMA_ESTUDIO"
    CHOICE_TIPO = ((TIPO_CURSO_APOYO, "Curso de apoyo"),
                   (TIPO_PROGRAMA_ESTUDIO, "Programa de estudio"),)

    codigo_institucional = models.CharField(max_length=25, unique=True)
    codigo_unesco = models.CharField(max_length=25, unique=True)
    nombre = models.TextField()
    tipo = models.CharField(max_length=25, choices=CHOICE_TIPO, default=TIPO_PROGRAMA_ESTUDIO)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


class AsignaturaNivel(models.Model):
    TIPO_OBLIGATORIA = "OBLIGATORIA"
    TIPO_OPTATIVA = "OPTATIVA"
    CHOICE_TIPO = ((TIPO_OBLIGATORIA, "Obligatoria"),
                   (TIPO_OPTATIVA, "Optativa"),)

    duracion = models.PositiveSmallIntegerField(null=True, blank=True)
    tipo = models.CharField(max_length=25, choices=CHOICE_TIPO, default=TIPO_OBLIGATORIA)

    asignatura = models.ForeignKey('Asignatura', related_name="asignaturas_nivel", on_delete=models.CASCADE)
    campo_formacion = models.ForeignKey('CampoFormacion', on_delete=models.PROTECT, null=True, blank=True)
    correquisitos = models.ManyToManyField('self', related_name="correquisito", blank=True)
    nivel = models.ForeignKey('Nivel', on_delete=models.CASCADE, related_name="asignaturas")
    prerrequisitos = models.ManyToManyField('self', related_name="postrrequisito", blank=True, symmetrical=False)

    class Meta:
        verbose_name_plural = 'Asignaturas de nivel'

    def __str__(self):
        return self.asignatura.nombre

    def actualizar_duracion(self):
        """
        Actualiza la duración de la asignatura nivel de acuerdo a la sumatoria de las asignaturas componentes
        :return:
        """
        self.duracion = self.asignaturas_componente.aggregate(total=models.Sum('duracion')).get('total') or 0
        self.save()


    def get_correquisitos_ids(self):
        """
        Retorna los ids de los correquisitos de la asignatura nivel
        :return:
        """
        return self.correquisitos.values_list('id', flat=True)


    def get_prerrequisitos_ids(self):
        """
        Retorna los ids de los prerrequisitos de la asignatura nivel
        :return:
        """
        return self.prerrequisitos.values_list('id', flat=True)


    def validate_unique(self, *args, **kwargs):
        """
        Valida que la asignatura sea asignada al pensum una sola vez
        :param args:
        :param kwargs:
        :return:
        """
        super(AsignaturaNivel, self).validate_unique(*args, **kwargs)
        asignatura = self.__class__.objects.filter(asignatura=self.asignatura, nivel__pensum=self.nivel.pensum).exclude(
            id=self.id)
        if asignatura.exists():
            raise ValidationError(
                message='Error, la asignatura ya está agregada en el pensum: Nivel: %s' % asignatura.first().nivel,
                code='unique_together',
            )


class AsignaturaComponente(models.Model):
    duracion = models.PositiveSmallIntegerField()

    asignatura_nivel = models.ForeignKey('AsignaturaNivel', on_delete=models.CASCADE,
                                         related_name='asignaturas_componente')
    componente_aprendizaje = models.ForeignKey('ComponenteAprendizaje', on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Componente de asignatura'
        verbose_name_plural = 'Componentes de asignatura'

    def save(self, *args, **kwargs):
        """
        Al guardar un registro, actualiza la duración total de la asignatura nivel
        :param args:
        :param kwargs:
        :return:
        """
        super(AsignaturaComponente, self).save(*args, **kwargs)
        self.asignatura_nivel.actualizar_duracion()

class Autoridad(models.Model):
    activo = models.BooleanField(default=False)
    abreviatura = models.CharField(max_length=25)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(null=True, blank=True)
    funcionario = models.ForeignKey('talento_humano.Funcionario', on_delete=models.PROTECT)
    referencia_ingreso = models.TextField(max_length=250)
    referencia_salida = models.TextField(null=True, blank=True, max_length=250)

    class Meta:
        ordering = ['-activo', 'fecha_inicio']


class AutoridadFacultad(Autoridad):
    TIPO_DECANO = "DECANO"
    TIPO_SECRETARIO_ABOGADO = "SECRETARIO_ABOGADO"
    CHOICE_TIPO = ((TIPO_DECANO, "Decano(a)"),
                   (TIPO_SECRETARIO_ABOGADO, "Secretario(a) abogado(a)"),)

    tipo = models.CharField(max_length=25, choices=CHOICE_TIPO, default=TIPO_SECRETARIO_ABOGADO)

    facultad = models.ForeignKey('Facultad', on_delete=models.CASCADE, related_name='autoridades_facultad')

    class Meta:
        ordering = ['-activo', 'tipo', 'fecha_inicio']
        verbose_name = 'Autoridad de facultad'
        verbose_name_plural = 'Autoridades de facultad'

    def __str__(self):
        return "%s %s" % (self.funcionario, self.tipo)


class AutoridadProgramaEstudio(Autoridad):
    TIPO_DIRECTOR = "DIRECTOR"
    TIPO_GESTOR = "GESTOR "
    TIPO_SECRETARIO = "SECRETARIO"
    CHOICE_TIPO = ((TIPO_DIRECTOR, "Director(a)"),
                   (TIPO_GESTOR, "Gestor(a)"), (TIPO_SECRETARIO, "Secretario(a)"),)
    NUMERO_ACTIVOS = {TIPO_DIRECTOR: 1, TIPO_GESTOR: 1, TIPO_SECRETARIO: 2}

    tipo = models.CharField(max_length=25, choices=CHOICE_TIPO, default=TIPO_SECRETARIO)

    programa_estudio = models.ForeignKey('ProgramaEstudio', on_delete=models.CASCADE,
                                         related_name='autoridades_programa_estudio')

    class Meta:
        ordering = ['-activo', 'tipo', 'fecha_inicio']
        verbose_name = 'Autoridad de programa de estudio'
        verbose_name_plural = 'Autoridades de programa de estudio'

    def __str__(self):
        return "%s %s" % (self.funcionario, self.tipo)


class CampoFormacion(models.Model):
    nombre = models.TextField()

    nivel_formacion = models.ForeignKey('NivelFormacion', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Campo de formación'
        verbose_name_plural = 'Campos de formación'
        ordering = ['nivel_formacion__regimen']

    def __str__(self):
        return '%s - %s' % (self.nivel_formacion, self.nombre)


class ComponenteAprendizaje(models.Model):
    codigo = models.CharField(max_length=25)
    nombre = models.CharField(max_length=100)
    regimen = models.CharField(max_length=25, choices=CHOICE_REGIMEN, default=REGIMEN_2013)

    class Meta:
        ordering = ['regimen', 'nombre']
        verbose_name = 'Componente de aprendizaje'
        verbose_name_plural = 'Componentes de aprendizaje'

    def __str__(self):
        return self.nombre


class Facultad(models.Model):
    nombre = models.TextField()
    siglas = models.CharField(max_length=25)

    class Meta:
        verbose_name_plural = 'Facultades'

    def __str__(self):
        return self.nombre


class NivelFormacion(models.Model):
    ESTADO_ACTIVO = "ACTIVO"
    CHOICE_ESTADO = ((ESTADO_ACTIVO, "Activo"),)

    descripcion = models.TextField(null=True, blank=True)
    estado = models.CharField(max_length=25, choices=CHOICE_ESTADO, default=ESTADO_ACTIVO)
    nombre = models.TextField()
    regimen = models.CharField(max_length=25, choices=CHOICE_REGIMEN, default=REGIMEN_2013)

    class Meta:
        verbose_name = 'Nivel de formación'
        verbose_name_plural = 'Niveles de formación'

    def __str__(self):
        return '%s (%s)' % (self.nombre, self.get_regimen_display())


class Nivel(models.Model):
    numero = models.PositiveSmallIntegerField()

    organizacion_curricular = models.ForeignKey('OrganizacionCurricular', on_delete=models.PROTECT, null=True, blank=True)
    pensum = models.ForeignKey('Pensum', on_delete=models.CASCADE, related_name='niveles')

    class Meta:
        ordering = ['pensum__id', 'numero']
        unique_together = ('numero', 'pensum')
        permissions = (('add_asignaturanivel', 'Puede agregar asignaturas al nivel'),)
        verbose_name_plural = 'Niveles'

    def __str__(self):
        return str(self.numero)

    def get_prerrequisitos_posibles(self, asignatura_nivel=None):
        """
        Permite obtener los prerequisitos posibles de un nivel del pensum
        :param asignatura_nivel: Si viene se excluye los prerequisitos ya establecidos
        :return:
        """
        prerrequisitos = AsignaturaNivel.objects.filter(nivel__pensum=self.pensum, nivel__numero__lt=self.numero)
        if asignatura_nivel:
            prerrequisitos = prerrequisitos.exclude(id__in=asignatura_nivel.get_prerrequisitos_ids())
        return prerrequisitos


class OrganizacionCurricular(models.Model):
    nombre = models.TextField()

    nivel_formacion = models.ForeignKey('NivelFormacion', on_delete=models.CASCADE)

    class Meta:
        ordering = ['nivel_formacion__regimen']
        verbose_name_plural = 'Organizaciones curriculares'

    def __str__(self):
        return self.nombre


class Pensum(models.Model):
    DURACION_UNIDAD_CREDITO = "CREDITO"
    DURACION_UNIDAD_HORA = "HORA"
    CHOICE_DURACION_UNIDAD = ((DURACION_UNIDAD_CREDITO, "Crédito"), (DURACION_UNIDAD_HORA, "Hora"),)

    ORGANIZACION_CICLO = "CICLO"
    CHOICE_ORGANIZACION = ((ORGANIZACION_CICLO, "Ciclo"),)

    TIPO_COMPONENTE = "COMPONENTE"
    CHOICE_TIPO = ((TIPO_COMPONENTE, "Por componentes"),)

    duracion_unidad = models.CharField(max_length=25, choices=CHOICE_DURACION_UNIDAD, default=DURACION_UNIDAD_HORA)
    editable = models.BooleanField(default=False)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(null=True, blank=True)
    nombre = models.TextField()

app/academico/models/periodo_academico.py
from django.db import models

class OfertaAcademica(models.Model):
    ESTADO_ACTIVO = "ACTIVO"
    ESTADO_CERRADO = "CERRADO"
    ESTADO_INACTIVO = "INACTIVO"
    CHOICE_ESTADO = ((ESTADO_ACTIVO, "Activo"),
                     (ESTADO_CERRADO, "Cerrado"),
                     (ESTADO_INACTIVO, "Inactivo"),)

    estado = models.CharField(max_length=25, choices=CHOICE_ESTADO, default=ESTADO_INACTIVO)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    nombre = models.TextField()

    periodo_academico = models.ForeignKey('PeriodoAcademico', on_delete=models.CASCADE,
                                          related_name='ofertas_academicas')
    class Meta:
        verbose_name = 'Oferta académica'
        verbose_name_plural = 'Ofertas académicas'

    def __str__(self):
        return self.nombre


class OfertaPensum(models.Model):
    oferta_academica = models.ForeignKey('OfertaAcademica', on_delete=models.CASCADE, related_name='ofertas_pensum')
    pensum = models.ForeignKey('Pensum', on_delete=models.PROTECT, related_name='ofertas_pensum')


    class Meta:
        permissions = (('add_ofertaasignaturanivel', 'Puede ofertar asignaturas'),)
        verbose_name = 'Oferta de pensum'
        verbose_name_plural = 'Ofertas de pensum'


class OfertaAsignaturaNivel(models.Model):
    asignatura_nivel = models.ForeignKey('AsignaturaNivel', on_delete=models.PROTECT, related_name='ofertas_asignatura_nivel')
    oferta_pensum = models.ForeignKey('OfertaPensum', on_delete=models.CASCADE, related_name='ofertas_asignatura_nivel')

    class Meta:
        verbose_name = 'Oferta de asignatura nivel'
        verbose_name_plural = 'Ofertas de asignatura nivel'


class PeriodoAcademico(models.Model):
    asistencia_minima_aprobar = models.PositiveSmallIntegerField() # En porcentaje (%)
    nombre = models.TextField()
    nota_minima_aprobar = models.PositiveSmallIntegerField()

    periodo_lectivo = models.ForeignKey('core.CatalogoItem',
                                       limit_choices_to={'catalogo__codigo': 'PERIODO_ACADEMICO_PERIODO_LECTIVO'},
                                       on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Período académico'
        verbose_name_plural = 'Períodos académicos'
        ordering = ['periodo_lectivo__nombre', 'nombre']

    def __str__(self):
        return self.nombre


class PeriodoMatricula(models.Model):
    TIPO_ORDINARIA = "ORDINARIA"
    TIPO_EXTRAORDINARIA = "EXTRAORDINARIA"
    TIPO_ESPECIAL = "ESPECIAL"
    CHOICE_TIPO = ((TIPO_ORDINARIA, "Ordinaria"),
                   (TIPO_EXTRAORDINARIA, "Extraordinaria"),
                   (TIPO_ESPECIAL, "Especial"),)

    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    tipo = models.CharField(max_length=25, choices=CHOICE_TIPO, default=TIPO_ORDINARIA)

    oferta_academica = models.ForeignKey('OfertaAcademica', on_delete=models.CASCADE, related_name='periodos_matricula')

    class Meta:
        unique_together = ('tipo', 'oferta_academica')
        verbose_name = 'Período de matrícula'
        verbose_name_plural = 'Períodos de matrícula'

app/academico/models/unesco.py
from django.db import models

class CampoAmplio(models.Model):
    codigo = models.CharField(max_length=25, unique=True)
    nombre = models.TextField()

    def __str__(self):
        return self.nombre


class CampoDetallado(models.Model):
    codigo = models.CharField(max_length=25)
    nombre = models.TextField()

    campo_especifico = models.ForeignKey('CampoEspecifico', on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre + ' - ' + str(self.campo_especifico) + ' - ' + str(self.campo_especifico.campo_amplio)


class CampoEspecifico(models.Model):
    codigo = models.CharField(max_length=25)
    nombre = models.TextField()

    campo_amplio = models.ForeignKey('CampoAmplio', on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

app/academico/templates/academico/asignatura_nivel/detalle.html
{% extends 'layout.html' %}

{% block estilos %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/academico/componente.css' %}">
{% endblock estilos %}


{% block titulo %}
    Asignatura
{% endblock %}

{% block migas %}
    {% include 'navegacion.html' %}
{% endblock %}

{% block contenido %}
    {% load guardian_tags %}
    {% get_obj_perms request.user for asignatura_nivel as "asignaturanivel_perms" %}
    {% get_obj_perms request.user for asignatura_nivel.nivel as "nivel_perms" %}
    {% get_obj_perms request.user for asignatura_nivel.nivel.pensum as "pensum_perms" %}
    <div class="card card-box">
        <div class="card-head">
            <header>{{ 'academico.AsignaturaNivel'|verbose_name|capfirst  }}</header>
            <div class="tools">
                <button class="btn btn-info"
                        data-toggle="modal"
                        data-target="#modal-asignatura-nivel-editar"
                        {% if not perms.academico.change_asignaturanivel and not 'change_asignaturanivel' in asignaturanivel_perms %}
                            disabled
                        {% endif %}>
                    <i class="fa fa-edit"></i>Editar
                </button>
                <a {% if perms.academico.delete_asignaturanivel or 'delete_asignaturanivel' in asignaturanivel_perms  %}
                    class="btn btn-danger"
                    href="{% url 'academico:asignatura_nivel_eliminar' asignatura_nivel.id %}"
                    onclick="return confirm('¿Está seguro de eliminar el registro?')"
                {% else %}
                    class="btn btn-danger disabled"
                {% endif %}>
                    <i class="fa fa-trash-o"></i>Eliminar
                </a>
            </div>
        </div>
        <div class="card-body ">
            <div class="header">
                <div class="text-center">
                    <h4>{{ asignatura_nivel.asignatura.nombre }}</h4>
                </div>
            </div>
            <div class="form-group form-inline text-left">
                <span class="col-sm-2">Asignatura:</span>
                <div class="col-sm-10">
                    <h5>
                        <a {% if perms.academico.view_asignatura %}
                            href="{% url 'academico:asignatura_detalle' asignatura_nivel.asignatura.id %}"
                        {% endif %}>
                            {{ asignatura_nivel.asignatura.nombre }}
                            {% if asignatura_nivel.asignatura.codigo_institucional and asignatura_nivel.asignatura.codigo_unesco %}
                                ({{ asignatura_nivel.asignatura.codigo_institucional }}-
                                {{ asignatura_nivel.asignatura.codigo_unesco }})
                            {% endif %}
                        </a>
                    </h5>
                </div>
                <span class="col-sm-2">Pensum:</span>
                <div class="col-sm-10">
                    <h5>
                        <a {% if perms.academico.view_pensum or 'view_pensum' in pensum_perms %}
                            href="{% url 'academico:pensum_detalle' asignatura_nivel.nivel.pensum.id %}"
                        {% endif %}>
                            {{ asignatura_nivel.nivel.pensum.nombre }}
                        </a>
                    </h5>
                </div>
                <span class="col-sm-2">Nivel:</span>
                <div class="col-sm-10">
                    <h5>
                        <a {% if perms.academico.view_nivel or 'view_nivel' in nivel_perms %}
                            href="{% url 'academico:nivel_detalle' asignatura_nivel.nivel.id %}"
                        {% endif %}>
                            {{ asignatura_nivel.nivel.numero }} {{ asignatura_nivel.nivel.pensum.get_organizacion_display }}
                        </a>
                    </h5>
                </div>
                <span class="col-sm-2">Campo de Formación:</span>
                <div class="col-sm-10">
                    <h5>{{ asignatura_nivel.campo_formacion.nombre }}</h5>
                </div>
                <span class="col-sm-2">Duración:</span>
                <div class="col-sm-4">

                    <h5><span id="asignatura-nivel-duracion"> {{ asignatura_nivel.duracion }} </span>
                        {{ asignatura_nivel.nivel.pensum.get_duracion_unidad_display }}{{ asignatura_nivel.duracion|pluralize }}
                    </h5>
                </div>
                <span class="col-sm-2">Tipo:</span>
                <div class="col-sm-4">
                    <h5>{{ asignatura_nivel.tipo }}</h5>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4>Componentes</h4>
                </div>
                <div class="card-body padre-item"
                     data-guardar-url="{% url 'academico:asignatura_componente_guardar' %}">
                    {% include 'academico/asignatura_componente/fragmento_lista.html' with asignaturas_componente=asignatura_nivel.asignaturas_componente.all %}
                </div>
            </div>
            {% if prerrequisitos_values %}
                <div class="card">
                    <div class="card-header">
                        <h4>Prerrequisitos
                            <button class="btn btn-circle btn-info btn-sm pull-right"
                                    data-toggle="modal" data-target="#modal-prerrequisito-editar"
                                    {% if not perms.academico.change_asignaturanivel and not 'change_asignaturanivel' in asignaturanivel_perms %} disabled {% endif %}>
                                <i class="fa fa-plus-circle"></i> Editar
                            </button>
                        </h4>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            {% for asignatura in asignatura_nivel.prerrequisitos.all %}
                                {% get_obj_perms request.user for asignatura as "asignatura_perms" %}
                                <a class="list-group-item list-group-item-action"
                                        {% if perms.academico.view_asignaturanivel  or "view_asignaturanivel" in asignatura_perms %}
                                   href="{% url 'academico:asignatura_nivel_detalle' asignatura.id %}"
                                        {% endif %}>
                                    {{ asignatura.asignatura.nombre }} - Nivel {{ asignatura.nivel.numero }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if correquisitos_values %}
                <div class="card">
                    <div class="card-header">
                        <h4>Correquisitos
                            <button class="btn btn-circle btn-info btn-sm pull-right"
                                    data-toggle="modal" data-target="#modal-correquisito-editar"
                                    {% if not perms.academico.change_asignaturanivel  and not 'change_asignaturanivel' in asignaturanivel_perms %} disabled {% endif %}>
                                <i class="fa fa-plus-circle"></i> Editar
                            </button>
                        </h4>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            {% for asignatura in asignatura_nivel.correquisitos.all %}
                                {% get_obj_perms request.user for asignatura as "asignatura_perms" %}
                                <a class="list-group-item list-group-item-action"
                                        {% if perms.academico.view_asignaturanivel or "view_asignaturanivel" in asignatura_perms %}
                                   href="{% url 'academico:asignatura_nivel_detalle' asignatura.id %}"
                                        {% endif %}>
                                    {{ asignatura.asignatura.nombre }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    {% include 'academico/asignatura_nivel/modal_editar.html' with nivel=asignatura_nivel.nivel %}
    {% include 'academico/asignatura_nivel/modal_editar_prerrequisito.html' %}
    {% include 'academico/asignatura_nivel/modal_editar_correquisito.html' %}

{% endblock contenido %}

{% block javascript %}
    {% load staticfiles %}
    <script src="{% static 'js/js_cookie.js' %}"></script>
    <script src="{% static 'js/academico/componente.js' %}?v=1.0"></script>
{% endblock javascript %}

app/academico/templates/academico/asignatura_nivel/fragmento_lista.html
{% load guardian_tags %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Duración</th>
            <th>Acción</th>
        </tr>
        </thead>
        <tbody>
        {% for asignatura_nivel in asignaturas_nivel %}
            {% get_obj_perms request.user for asignatura_nivel as "asignaturanivel_perms" %}
            <tr>
                <td>
                    <a {% if perms.academico.view_asignaturanivel or 'view_asignaturanivel' in asignaturanivel_perms %}
                        href="{% url 'academico:asignatura_nivel_detalle' asignatura_nivel.id %}"
                    {% endif %}>
                        {{ asignatura_nivel.asignatura.nombre }}
                    </a>
                </td>
                <td>
                    {% if asignatura_nivel.duracion %}
                        {{ asignatura_nivel.duracion }}
                    {% else %}
                        0
                    {% endif %}
                    {{ asignatura_nivel.nivel.pensum.get_duracion_unidad_display }}{{ asignatura_nivel.duracion|pluralize }}
                <td>
                    <a title="Eliminar"
                            {% if perms.academico.delete_asignaturanivel or 'delete_asignaturanivel' in asignaturanivel_perms %}
                       class="btn btn-outline-danger"
                       onclick="return confirm('¿Está seguro de eliminar el registro?')"
                       href="{% url 'academico:asignatura_nivel_eliminar' asignatura_nivel.id %}"
                            {% else %}
                       class="btn btn-outline-danger disabled"
                            {% endif %}>
                        <i class="fa fa-trash-o"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

app/academico/templates/academico/asignatura_nivel/modal_editar_correquisito.html
<div class="modal fade" id="modal-correquisito-editar">
    <form action="{% url 'academico:asignatura_nivel_guardar_correquisito' %}" method="POST" role="form"
          class="auto-validate">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ asignatura_nivel.id }}"/>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Correquisitos</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="asignatura">Asignatura:</label>
                        <h5>
                            {{ asignatura_nivel.asignatura.nombre }}
                        </h5>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Seleccione los correquisitos
                        </label>
                        <select name="correquisitos" id="select-correquisitos" class="form-control select2" multiple>
                            {% with correquisitos=asignatura_nivel.get_correquisitos_ids %}
                                {% for asignatura in correquisitos_values %}
                                    <option value="{{ asignatura.id }}"
                                            {% if asignatura.id in correquisitos %}
                                            selected {% endif %}>
                                        {{ asignatura.asignatura__nombre }}
                                        - Nivel {{ asignatura.nivel__numero }}
                                    </option>
                                {% endfor %}
                            {% endwith %}
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-ban"></i>Cancelar
                    </button>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>Guardar</button>
                </div>
            </div>
        </div>
    </form>
</div>