app/core/urls.py
from django.conf.urls import url

from app.core.utils import validador
from . import views
app_name = 'core'
urlpatterns = [
    url(r'^direccion/crear/(?P<persona_id>[\d]+)$', views.direccion_crear, name='direccion_crear'),
    url(r'^direccion/editar/(?P<id>[\d]+)$', views.direccion_editar, name='direccion_editar'),
    url(r'^direccion/eliminar/(?P<id>[\d]+)$', views.direccion_eliminar, name='direccion_eliminar'),
    url(r'^direccion/guardar/(?P<persona_id>[\d]+)$', views.direccion_guardar, name='direccion_guardar'),
    #agregados
    url(r'^direccion/crear_momentaneo/(?P<persona_id>[\d]+)$', views.direccion_crear_momentaneo, name='direccion_crear_momentaneo'),
    url(r'^direccion/editar_momentaneo/(?P<id>[\d]+)$', views.direccion_editar_momentaneo, name='direccion_editar_momentaneo'),
    url(r'^direccion/guardar_momentaneo/(?P<persona_id>[\d]+)$', views.direccion_guardar_momentaneo, name='direccion_guardar_momentaneo'),
    url(r'^direccion/basico_guardar/(?P<persona_id>[\d]+)$', views.direccion_basico_guardar, name='direccion_basico_guardar'),
    url(r'^direccion/basico_detalle/(?P<id>[\d]+)$', views.direccion_basico_detalle, name='direccion_basico_detalle'),

    url(r'^persona/editar/(?P<id>[\d]+)$', views.persona_editar, name='persona_editar'),
    url(r'^persona/guardar$', views.persona_guardar, name='persona_guardar'),
    ##agregados

    url(r'^persona/crear_basico/(?P<cedula>[\d]+)', views.persona_basico_registro, name='persona_basico_registro'),
    url(r'^persona/editar_momentaneo/(?P<id>[\d]+)$', views.persona_editar_momentaneo, name='persona_editar_momentaneo'),
    url(r'^persona/guardar_nuevo$', views.persona_guardar_momentaneo, name='persona_guardar_momentaneo'),
    url(r'^persona/listar_momentaneo/', views.persona_listar_momentaneo, name='persona_listar_momentaneo'),
    url(r'^persona/guardar_momentaneo$', views.persona_guardar_momentaneo_adm, name='persona_guardar_momentaneo_adm'),
    url(r'^persona/basico_guardar$', views.persona_basico_guardar, name='persona_basico_guardar'),

    url(r'^relacion/buscar/(?P<persona_id>[\d]+)$', views.relacion_buscar, name='relacion_buscar'),
    url(r'^relacion/crear/(?P<persona_id>[\d]+)$', views.relacion_crear, name='relacion_crear'),
    url(r'^relacion/editar/(?P<id>[\d]+)$', views.relacion_editar, name='relacion_editar'),
    url(r'^relacion/eliminar/(?P<id>[\d]+)$', views.relacion_eliminar, name='relacion_eliminar'),
    url(r'^relacion/guardar/(?P<persona_id>[\d]+)$', views.relacion_guardar, name='relacion_guardar'),

    url(r'^validar/campo-unico/', validador.validar_campo_unico, name='validar_campo_unico'),
    url(r'^validar/numero-documento/', validador.validar_numero_documento, name='validar_numero_documento'),
]

app/tesoreria/urls.py
from django.urls import path

from app.tesoreria import views

app_name = 'tesoreria'
urlpatterns = [
    path('index', views.index_tesoreria, name='index_tesoreria'),

    path('cliente/informacion_detallada/<int:id>', views.cliente_informacion_detallada,
         name='cliente_informacion_detallada'),
    path('cliente/lista', views.cliente_lista, name='cliente_lista'),
    path('cliente/lista-paginador', views.cliente_lista_paginador, name='cliente_lista_paginador'),

    path('comentario/detalle/<int:id>', views.comentario_detalle, name='comentario_detalle'),
    path('comentario/eliminar/<int:id>', views.comentario_eliminar, name='comentario_eliminar'),
    path('comentario/guardar', views.comentario_guardar, name='comentario_guardar'),

    path('cuenta_cobrar/buscar', views.cuenta_cobrar_buscar, name='cuenta_cobrar_buscar'),
    path('cuenta_cobrar/detalle/<int:id>', views.cuenta_cobrar_detalle, name='cuenta_cobrar_detalle'),
    path('cuenta_cobrar/eliminar/<int:id>', views.cuenta_cobrar_eliminar, name='cuenta_cobrar_eliminar'),
    path('cuenta_cobrar/crear', views.cuenta_cobrar_crear, name='cuenta_cobrar_crear'),
    path('cuenta_cobrar/guardar2', views.cuenta_cobrar_guardar, name='cuenta_cobrar_guardar2'),
    path('cuenta_cobrar/guardar2/<int:id>', views.cuenta_cobrar_guardar, name='cuenta_cobrar_guardar2'),
    path('cuenta_cobrar/listar', views.cuenta_cobrar_listar, name='cuenta_cobrar_listar'),
    path('cuenta_cobrar/lista-paginador', views.cuenta_cobrar_lista_paginador, name='cuenta_cobrar_lista_paginador'),


    path('cuenta_cobrar/abonos/eliminar/<int:id>', views.abono_eliminar, name='abono_eliminar'),
    path('cuenta_cobrar/abonos/guardar', views.abono_guardar, name='abono_guardar'),
    path('cuenta_cobrar/abonos/imprimir/<int:id>', views.abono_imprimir, name='abono_imprimir'),
    path('cuenta_cobrar/abonos/calcular', views.cuenta_cobrar_get_saldo, name='cuenta_cobrar_get_saldo'),



    path('interes_mensual/eliminar/<int:id>', views.interes_mensual_eliminar, name='interes_mensual_eliminar'),
    path('interes_mensual/guardar', views.interes_mensual_guardar, name='interes_mensual_guardar'),


    path('tasa_interes/detalle/<int:id>', views.tasa_interes_detalle, name='tasa_interes_detalle'),
    path('tasa_interes/eliminar/<int:id>', views.tasa_interes_eliminar, name='tasa_interes_eliminar'),
    path('tasa_interes/aplicar/<int:id>', views.tasa_interes_aplicar, name='tasa_interes_aplicar'),
    path('tasa_interes/guardar', views.tasa_interes_guardar, name='tasa_interes_guardar'),
    path('tasa_interes/listar', views.tasa_interes_listar, name='tasa_interes_listar'),
    path('tasa_interes/lista-paginador', views.tasa_interes_lista_paginador, name='tasa_interes_lista_paginador'),


]

siaa/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from siaa import views

urlpatterns = [
    path('', views.index, name='index'),
    path(r'admin/', admin.site.urls),
    path('autenticacion/', include('app.autenticacion.urls')),
    path('academico/', include('app.academico.urls')),
    path('cientifica/', include('app.cientifica.urls')),
    path('core/', include('app.core.urls')),
    path('hveterinario/', include('app.hveterinario.urls')),
    path('reporte/', include('app.reporte.urls')),
    path('organico/', include('app.organico.urls')),
    path('planificacion/', include('app.planificacion.urls')),
    path('seguridad/', include('app.seguridad.urls')),
    path('seguridad-informacion/', include('app.seguridad_informacion.urls')),
    path('talento-humano/', include('app.talento_humano.urls')),
    path('tesoreria/', include('app.tesoreria.urls')),

    # Url de api
    path('api/v1/bienes/', include('api.bienes.urls')),
    path('api/v1/configuracion/', include('api.configuracion.urls')),
    path('api/v1/core/', include('api.core.urls')),
    path('api/v1/curricular/', include('api.curricular.urls' )),
    path('api/v1/organico/', include('api.organico.urls')),
    path('api/v1/recaudacion/', include('api.recaudacion.urls')),
    path('api/v1/seguridad/', include('api.seguridad.urls')),
    path('api/v1/talento-humano/', include('api.talento_humano.urls')),

    #Url servicios externos
    path('api/v1/bsg/', include(('api.bsg.urls', 'api_bsg'))),
    path('api/v1/banco/', include(('api.banco.urls', 'api_banco'))),
    path('api/v1/eventos/', include(('api.eventos.urls', 'api_eventos'))),
    path('api/v1/google/', include(('api.google.urls', 'api_google'))),
    path('api/v1/ldap/', include(('api.ldap.urls', 'api_ldap'))),
    path('api/v1/sga/', include(('api.sga.urls', 'api_sga'))),
]

app/tesoreria/views.py
import calendar
from _decimal import Decimal
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponseServerError
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.dateparse import parse_date
from django.views.decorators.http import require_http_methods

from app.core.dto.datatable import DataTableParams
from app.core.models import Persona
from app.core.utils.enums import MensajesEnum
from app.tesoreria.forms import CuentaCobrarForm, ComentarioForm, AbonoForm, TasaInteresForm, \
    InteresMensualForm
from app.tesoreria.layer.application.cuenta_cobrar_app_service import CuentaCobrarAppService
from app.tesoreria.models import CuentaCobrar, Comentario, Abono, TasaInteres, InteresMensual
from app.reporte.utils import pdf as pdfUtil

from app.tesoreria.utils.datatable import DatatableBuscar


@login_required
def index_tesoreria(request):
    """
    Index de la sección tesoreria
    :param request:
    :return:
    """
    navegacion = ('Módulo académico',
                  [('Tesoreria', reverse('tesoreria:index_tesoreria'))])
    return render(request, 'tesoreria/index_tesoreria.html', locals())


@login_required
@permission_required('tesoreria.change_abono', raise_exception=True, )
@require_http_methods(['POST'])
def abono_guardar(request):
    next = request.POST.get('next')
    id = request.POST.get('id')
    id_cli = request.POST.get('cuenta_cobrar')
    monto = Decimal(request.POST.get('monto'))
    cuenta_cobrar = CuentaCobrar.objects.get(id=str(id_cli))
    saldo = cuenta_cobrar.saldo
    interes = cuenta_cobrar.interes

    if InteresMensual.objects.filter(cuenta_cobrar=cuenta_cobrar,
                                     fecha_inicio__gte=request.POST.get('fecha_pago')).exists():
        cuenta_cobrar = CuentaCobrar.objects.get(id=str(id_cli))
        total = Decimal(cuenta_cobrar.saldo) + Decimal(cuenta_cobrar.interes)
        aux = CuentaCobrarAppService.recalculo(request)
        request.POST._mutable = True
        request.POST['interes'] = Decimal(round(aux, 2))
        request.POST._mutable = False
        abono = Abono()
        abono_form = AbonoForm(request.POST, instance=abono)

        if abono_form.is_valid() and abono.monto <= total:
            abono_form.save()
            messages.success(request, MensajesEnum.ACCION_GUARDAR.value)
        else:
            messages.warning(request, MensajesEnum.ABONO_ERROR.value)
        return redirect(next)
    else:
        aux_interes = 0.00

        if interes > 0:
            aux_abo_int = interes - monto

            if aux_abo_int < 0:
                aux_abo_int = aux_abo_int * -1
                aux = monto - aux_abo_int
                aux_interes = 0
            else:
                aux = monto
                aux_interes = aux_abo_int
                aux_abo_int = 0

            request.POST._mutable = True
            request.POST['interes'] = Decimal(round(aux, 2))
            request.POST._mutable = False
        else:
            aux_abo_int = monto
        total = Decimal(saldo) - Decimal(aux_abo_int)

        if id:
            abono = get_object_or_404(Abono, id=id)
        else:
            abono = Abono()
        abono_form = AbonoForm(request.POST, instance=abono)
        if abono_form.is_valid() and monto <= (
                cuenta_cobrar.saldo + cuenta_cobrar.interes) and not Abono.objects.filter(
            fecha_pago__gt=abono.fecha_pago).exists():
            fecha_pago_abono = datetime.datetime.strptime(request.POST.get('fecha_pago'), '%Y-%m-%d')
            saldo_total = CuentaCobrarAppService.get_total_saldo(cuenta_cobrar, fecha_pago_abono)

            if Decimal(monto) == Decimal(round(saldo_total, 2)):
                boll = 0
                fecha_cancelacion = datetime.datetime.now()
                CuentaCobrar.objects.values('estado', 'fecha_cancelacion', 'interes', 'saldo').filter(id=id_cli).update(
                    estado=False,
                    fecha_cancelacion=fecha_cancelacion, interes=boll, saldo=boll)
                try:
                    intereses_mensuales = InteresMensual.objects.filter(cuenta_cobrar=cuenta_cobrar)
                except intereses_mensuales.DoesNotExist:
                    intereses_mensuales = None
                if intereses_mensuales != None:

                    for interesmensual in intereses_mensuales:
                        InteresMensual.objects.values('pagado').filter(id=interesmensual.id).update(pagado=True)
            else:
                CuentaCobrar.objects.values('saldo', 'interes').filter(id=id_cli).update(saldo=total,
                                                                                         interes=aux_interes)
            abono_form.save()
            messages.success(request, MensajesEnum.ACCION_GUARDAR.value)
        else:
            messages.warning(request, MensajesEnum.ABONO_ERROR.value)
        return redirect(next)


@login_required
@permission_required('tesoreria.delete_abono', raise_exception=True, )
def abono_eliminar(request, id):
    abono = get_object_or_404(Abono, id=id)
    cuenta_cobrar = CuentaCobrar.objects.get(id=str(abono.cuenta_cobrar_id))
    monto = abono.monto
    interes_abono = abono.interes
    diferencia = monto - interes_abono
    saldo = cuenta_cobrar.saldo
    total = saldo + diferencia
    ultimo_abono = Abono.objects.filter(cuenta_cobrar=cuenta_cobrar).last()

    if ultimo_abono.id == abono.id:
        try:
            interes_mensual = InteresMensual.objects.get(cuenta_cobrar=cuenta_cobrar,
                                                         fecha_fin__year=abono.fecha_pago.year,
                                                         fecha_fin__month=abono.fecha_pago.month)

            intereses_mensuales = InteresMensual.objects.filter(cuenta_cobrar=cuenta_cobrar,
                                                                fecha_fin__gt=abono.fecha_pago).order_by('fecha_fin')
        except interes_mensual.DoesNotExist:
            interes_mensual = None
            intereses_mensuales = None

        if not interes_mensual == None:
            interes = (((Decimal(total) * Decimal(interes_mensual.tasa.tasa)) / 100))
            InteresMensual.objects.values('valor').filter(id=interes_mensual.id).update(valor=interes)
            interes_cuenta = 0

            for interesmensual in intereses_mensuales:

                if interesmensual.id != interes_mensual.id:
                    interes_mes = (total * interesmensual.tasa.tasa) / 100
                    InteresMensual.objects.values('valor').filter(id=interesmensual.id).update(valor=interes_mes)

            intereses_mensuales = InteresMensual.objects.filter(cuenta_cobrar=cuenta_cobrar)

            for interesmensual in intereses_mensuales:
                interes_cuenta = interes_cuenta + interesmensual.valor

            CuentaCobrar.objects.values('interes').filter(id=abono.cuenta_cobrar.id).update(saldo=total,
                                                                                            interes=interes_cuenta)

        if total > 0:
            CuentaCobrar.objects.values('estado').filter(id=abono.cuenta_cobrar_id).update(estado=True)

        try:
            if abono.delete():
                messages.success(request, MensajesEnum.ACCION_ELIMINAR.value)
                return redirect('tesoreria:cuenta_cobrar_detalle', abono.cuenta_cobrar_id)
            else:
                messages.warning(request, MensajesEnum.ACCION_ELIMINAR_ERROR.value)
                return redirect('tesoreria:cuenta_cobrar_detalle', id)
        except Exception as e:
            messages.warning(request, str(e))
            return HttpResponseServerError(render(request, '500.html'))
    else:
        messages.warning(request, "Solo puedes eliminar el úlmino abono")
        return redirect('tesoreria:cuenta_cobrar_detalle', abono.cuenta_cobrar_id)


@login_required
@permission_required('tesoreria.view_abono', raise_exception=True, )
def abono_imprimir(request, id):
    abono = get_object_or_404(Abono, id=id)
    datos = dict(

        cliente=abono.cuenta_cobrar.cliente.get_nombres_completos(),
        fecha_pago=abono.fecha_pago,
        forma_pago=abono.forma_pago,
        referencia=abono.referencia,
        concepto=abono.concepto,
        monto=abono.monto,
        interes=abono.interes,
        saldo=abono.cuenta_cobrar.saldo,
        observacion=abono.observacion

    )
    return pdfUtil.generar_reporte('tesoreria_abono', datos, 'pdf', request)


@login_required
@permission_required('tesoreria.change_cuentacobrar', raise_exception=True)
def cliente_lista(request):
    """
    Lista las clientes
    :param request:
    :return:
    """
    navegacion = ('Modulo financiero',
                  [('Tesorería', reverse('tesoreria:index_tesoreria')),
                   ('Clientes', None)])

    return render(request, 'tesoreria/cliente/lista.html', locals())


@login_required
@require_http_methods(["POST"])
@permission_required('tesoreria.change_cuentacobrar', raise_exception=True, )
def cliente_lista_paginador(request):
    """
    Lista los clientes con la paginación de datatable
    :param request:
    :return:
    """
    try:
        params = DataTableParams(request, **request.POST)
        DatatableBuscar.cliente(params)
        data = params.items.values('id', 'numero_documento', 'primer_apellido', 'segundo_apellido', 'primer_nombre',
                                   'segundo_nombre',
                                   'correo_electronico').all()
        result = params.result(list(data))
        return JsonResponse(result)

    except Exception as e:
        return HttpResponseServerError(e)


@login_required

app/tesoreria/templates/tesoreria/persona/editar_direccion.html
{% extends 'layout.html' %}

{% block titulo %}
    Crear Dirección
{% endblock %}

{% block migas %}
    {% include 'navegacion.html' with navegacion=navegacion %}
{% endblock %}

{% block contenido %}
    <div class="card card-box">
        <div class="card-head">
            <header>Datos de la dirección</header>
        </div>
        <div class="card-body ">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <form id="frmDireccion" action="{% url 'core:direccion_guardar_momentaneo' persona.id %}"
                          class="form-horizontal auto-validate" method="POST" name="form">
                        {% csrf_token %}
                        <table class="table table-hover">
                            {% if direccion %}
                                <tr>
                                    <td><span class="error">(*) </span>Parroquia</td>
                                    <td>
                                        <select class="form-control select2" id="parroquia_id" name="parroquia" value="{% if  direccion.parroquia %} {{ direccion.parroquia.id }} {% else %} '' {% endif %}" required>
                                            <option value="" selected="selected">---------</option>
                                        </select>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td><span class="error">(*) </span> País</td>
                                    <td>
                                        <select class="form-control select2" id="pais_id" name="pais" required>
                                            <option value="" selected="selected">---------</option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td><span class="error">(*) </span> Provincia</td>
                                    <td>
                                        <select class="form-control" id="provincia_id" name="provincia" required>
                                            <option value="" selected="selected">---------</option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td><span class="error">(*) </span> Cantón</td>
                                    <td>
                                        <select class="form-control" id="canton_id" name="canton" required>
                                            <option value="" selected="selected">---------</option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td><span class="error">(*) </span> Parroquia</td>
                                    <td>
                                        <select class="form-control" id="parroquia_id" name="parroquia" required>
                                            <option value="" selected="selected">---------</option>
                                        </select>
                                    </td>
                                </tr>
                            {% endif %}

                            <input type="hidden" name="next" value="{{ next }}">
                            <input type="hidden" name="id" value="{{ direccion.id }}"/>
                            {{ direccion_form }}

                        </table>
                        <div class="text-center">
                            <button type='submit' class='btn btn-primary m-r-20'>
                                <i class="fa fa-save"></i> Guardar
                            </button>
                            <a class='btn btn-default' href="{{ next }}#tab_direccion">
                                <i class="fa fa-ban"></i> Cancelar
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

{% block javascript %}
    {% load staticfiles %}
    <script src="{% static 'js/core/direccion_detalle.js' %}"></script>
{% endblock %}

app/tesoreria/templates/tesoreria/persona/editar_persona.html
{% extends 'layout.html' %}

{% block titulo %}
    Modificar Datos Personales:
{% endblock %}

{% block migas %}
    {% include 'navegacion.html'  with navegacion=navegacion %}
{% endblock %}

{% block contenido %}
    <div class="card card-box">
        <div class="card-head">
            <header>Datos personales</header>
        </div>
        <div class="card-body ">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <form action="{% url 'core:persona_guardar_momentaneo_adm' %}" class="form-horizontal auto-validate" method="POST">
                        {% csrf_token %}
                        <table class="table table-hover">
                            <input type="hidden" name="id" value="{{ persona.id }}">
                            <input type="hidden" name="next" value="{{ next }}">
                            {{ persona_form_administrador }}
                        </table>
                        <div class="text-center">
                            <button type='submit' class='btn btn-primary m-r-20'>
                                <i class="fa fa-save"></i> Guardar
                            </button>
                            <a class='btn btn-default' href="{{ next }}">
                                <i class="fa fa-ban"></i> Cancelar
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock contenido %}

{% block javascript %}
    {% load staticfiles %}
    <script src="{% static 'js/core/persona_detalle.js' %}"></script>
    <script type="text/javascript">
        var persona_validado_bsg = '{{persona.validado_bsg}}'
    </script>
{% endblock javascript %}

app/tesoreria/templates/tesoreria/persona/fragmento_detalle.html
<div class="table-responsive">
    <table class="table table-hover">
        <tbody>
        <tr>
            <th>{{ persona.tipo_documento|default:"" }}</th>
            <td>{{ persona.numero_documento|default:"" }}</td>
        </tr>
        <tr>
            <th>Primer nombre</th>
            <td>{{ persona.primer_nombre|default:"" }}</td>
        </tr>
        <tr>
            <th>Segundo nombre</th>
            <td>{{ persona.segundo_nombre|default:"" }}</td>
        </tr>
        <tr>
            <th>Primer apellido</th>
            <td>{{ persona.primer_apellido|default:"" }}</td>
        </tr>
        <tr>
            <th>Segundo apellido</th>
            <td>{{ persona.segundo_apellido|default:"" }}</td>
        </tr>
        
        <tr>
            <th>Correo electrónico personal</th>
            <td>{{ persona.correo_electronico|default:"" }}</td>
        </tr>
        
        </tbody>
    </table>
</div>

app/tesoreria/templates/tesoreria/persona/fragmento_lista.html
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    {% if usuario.estudiante %}
    {% include 'info_mensaje.html' with title="Estimado Usuario" text="Por favor ingrese la dirección de DOMICILIO Y NACIMIENTO" %}
    {% else %}
    {% include 'info_mensaje.html' with title="Estimado Usuario" text="Por favor ingrese la dirección de DOMICILIO Y TRABAJO obligatorio. El número de teléfono (ejm: 072547252), celular (ejm: 0912345678) y parroquia es obligatorio." %}
    {% endif %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Direciones
                <a href="{% url 'core:direccion_crear_momentaneo' persona.id %}?next={{request.path}}"
                   class="btn btn-info btn-circle btn-xs pull-right"
                   role="button">
                    <i class="fa fa-plus-circle"></i>Nuevo
                </a>
            </h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Tipo de Dirección</th>
                        <th>Calle Principal</th>
                        <th>Nro. de Casa</th>
                        <th>Calle Secundaria</th>
                        <th>Referencia</th>
                        <th>Teléfono Fijo</th>
                        <th>Teléfono Celular</th>
                        <th>Parroquia</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for direccion in persona.direccion_set.all %}
                    <tr>
                        <td>{{ direccion.tipo_direccion }}</td>
                        <td>{{ direccion.calle_principal| default:"" }}</td>
                        <td>{{ direccion.numero| default:"" }}</td>
                        <td>{{ direccion.calle_secundaria| default:"" }}</td>
                        <td>{{ direccion.referencia| default:"" }}</td>
                        <td>
                            {% if direccion.validar_telefono %}
                                {{ direccion.telefono| default:"" }}
                            {% else %}
                                <span class="text-danger">{{ direccion.telefono| default:"" }}</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if direccion.validar_celular %}
                                {{ direccion.celular| default:"" }}
                            {% else %}
                                 <span class="text-danger"> {{ direccion.celular| default:"" }}</span>
                            {% endif %}
                        </td>
                        <td>{{ direccion.parroquia | default:"" }}</td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-outline-info"
                                   title="Editar"
                                   href="{% url 'core:direccion_editar_momentaneo' direccion.id %}?next={{request.path}}">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <!--
                                <a class="btn btn-outline-danger"
                                   title="Eliminar"
                                   onclick="return confirm('¿Está seguro de eliminar el registro?')"
                                   href="{% url 'core:direccion_eliminar' direccion.id %}?next={{request.path}}">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                                -->
                            </div>
                        <td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>