app/tesoreria/urls.py
from django.urls import path

from app.tesoreria import views

app_name = 'tesoreria'
urlpatterns = [
    path('index', views.index_tesoreria, name='index_tesoreria'),

    path('cliente/informacion_detallada/<int:id>', views.cliente_informacion_detallada,
         name='cliente_informacion_detallada'),
    path('cliente/lista', views.cliente_lista, name='cliente_lista'),
    path('cliente/lista-paginador', views.cliente_lista_paginador, name='cliente_lista_paginador'),

    path('comentario/detalle/<int:id>', views.comentario_detalle, name='comentario_detalle'),
    path('comentario/eliminar/<int:id>', views.comentario_eliminar, name='comentario_eliminar'),
    path('comentario/guardar', views.comentario_guardar, name='comentario_guardar'),

    path('cuenta_cobrar/buscar', views.cuenta_cobrar_buscar, name='cuenta_cobrar_buscar'),
    path('cuenta_cobrar/detalle/<int:id>', views.cuenta_cobrar_detalle, name='cuenta_cobrar_detalle'),
    path('cuenta_cobrar/eliminar/<int:id>', views.cuenta_cobrar_eliminar, name='cuenta_cobrar_eliminar'),
    path('cuenta_cobrar/crear', views.cuenta_cobrar_crear, name='cuenta_cobrar_crear'),
    path('cuenta_cobrar/guardar2', views.cuenta_cobrar_guardar, name='cuenta_cobrar_guardar2'),
    path('cuenta_cobrar/guardar2/<int:id>', views.cuenta_cobrar_guardar, name='cuenta_cobrar_guardar2'),
    path('cuenta_cobrar/listar', views.cuenta_cobrar_listar, name='cuenta_cobrar_listar'),
    path('cuenta_cobrar/lista-paginador', views.cuenta_cobrar_lista_paginador, name='cuenta_cobrar_lista_paginador'),


    path('cuenta_cobrar/abonos/eliminar/<int:id>', views.abono_eliminar, name='abono_eliminar'),
    path('cuenta_cobrar/abonos/guardar', views.abono_guardar, name='abono_guardar'),
    path('cuenta_cobrar/abonos/imprimir/<int:id>', views.abono_imprimir, name='abono_imprimir'),
    path('cuenta_cobrar/abonos/calcular', views.cuenta_cobrar_get_saldo, name='cuenta_cobrar_get_saldo'),



    path('interes_mensual/eliminar/<int:id>', views.interes_mensual_eliminar, name='interes_mensual_eliminar'),
    path('interes_mensual/guardar', views.interes_mensual_guardar, name='interes_mensual_guardar'),


    path('tasa_interes/detalle/<int:id>', views.tasa_interes_detalle, name='tasa_interes_detalle'),
    path('tasa_interes/eliminar/<int:id>', views.tasa_interes_eliminar, name='tasa_interes_eliminar'),
    path('tasa_interes/aplicar/<int:id>', views.tasa_interes_aplicar, name='tasa_interes_aplicar'),
    path('tasa_interes/guardar', views.tasa_interes_guardar, name='tasa_interes_guardar'),
    path('tasa_interes/listar', views.tasa_interes_listar, name='tasa_interes_listar'),
    path('tasa_interes/lista-paginador', views.tasa_interes_lista_paginador, name='tasa_interes_lista_paginador'),


]

siaa/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from siaa import views

urlpatterns = [
    path('', views.index, name='index'),
    path(r'admin/', admin.site.urls),
    path('autenticacion/', include('app.autenticacion.urls')),
    path('academico/', include('app.academico.urls')),
    path('cientifica/', include('app.cientifica.urls')),
    path('core/', include('app.core.urls')),
    path('hveterinario/', include('app.hveterinario.urls')),
    path('reporte/', include('app.reporte.urls')),
    path('organico/', include('app.organico.urls')),
    path('planificacion/', include('app.planificacion.urls')),
    path('seguridad/', include('app.seguridad.urls')),
    path('seguridad-informacion/', include('app.seguridad_informacion.urls')),
    path('talento-humano/', include('app.talento_humano.urls')),
    path('tesoreria/', include('app.tesoreria.urls')),

    # Url de api
    path('api/v1/bienes/', include('api.bienes.urls')),
    path('api/v1/configuracion/', include('api.configuracion.urls')),
    path('api/v1/core/', include('api.core.urls')),
    path('api/v1/curricular/', include('api.curricular.urls' )),
    path('api/v1/organico/', include('api.organico.urls')),
    path('api/v1/recaudacion/', include('api.recaudacion.urls')),
    path('api/v1/seguridad/', include('api.seguridad.urls')),
    path('api/v1/talento-humano/', include('api.talento_humano.urls')),

    #Url servicios externos
    path('api/v1/bsg/', include(('api.bsg.urls', 'api_bsg'))),
    path('api/v1/banco/', include(('api.banco.urls', 'api_banco'))),
    path('api/v1/eventos/', include(('api.eventos.urls', 'api_eventos'))),
    path('api/v1/google/', include(('api.google.urls', 'api_google'))),
    path('api/v1/ldap/', include(('api.ldap.urls', 'api_ldap'))),
    path('api/v1/sga/', include(('api.sga.urls', 'api_sga'))),
]

app/tesoreria/models.py
import calendar
from datetime import date, timezone

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from decimal import Decimal

# Create your models here.
#from rest_framework.fields import CharField
from django.db.models import Q

from app.core.models import Persona


class CuentaCobrar(models.Model):
    TIPO_TITULO = "TITULO CREDITO"
    TIPO_OTRO = "OTROS"
    CHOICE_DOCUMENTO = ((TIPO_TITULO, "Titulo de crédito"), (TIPO_OTRO, "Otro"),)

    tipo_documento = models.CharField(max_length=30, choices=CHOICE_DOCUMENTO, default=TIPO_TITULO)
    estado = models.BooleanField(default=True)
    concepto = models.CharField(max_length=100)
    fecha_emision = models.DateField(verbose_name="Fecha de emision")
    fecha_vencimiento = models.DateField(verbose_name="Fecha de vencimiento")
    fecha_cancelacion = models.DateField(null=True, blank=True, verbose_name="Fecha de cancelacion")
    monto = models.DecimalField(max_digits=15, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    saldo = models.DecimalField(max_digits=15, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    interes = models.DecimalField(default=0, max_digits=15, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    cliente = models.ForeignKey(Persona, on_delete=models.PROTECT, related_name='cuentas_cobrar')
    numero_titulo = models.CharField(max_length=10)
    titulo = models.FileField(upload_to='tesoreria/')


    class Meta:
        verbose_name = "Cuenta por Cobrar"
        verbose_name_plural = "Cuentas por Cobrar"
        ordering = ['id']

    def __str__(self):
        return "%s" % self.concepto

    @staticmethod
    def buscar(criterio):
        """
        Buscar registros por criterios
        :param criterio:
        :return:
        """
        if criterio:
            p_criterio = criterio.split(" ")
            qset = Q()
            for i in p_criterio:
                qset = qset & (Q(cliente__primer_apellido__icontains=i) | Q(
                    cliente__segundo_apellido__icontains=i) | Q(
                    cliente__primer_nombre__icontains=i) | Q(
                    cliente__segundo_nombre__icontains=i) | Q(
                    cliente__numero_documento__icontains=i))
        return CuentaCobrar.objects.filter(qset).distinct()

class Abono(models.Model):
    FORMA_PAGO_EFECTIVO = "Efectivo"
    FORMA_PAGO_CHEQUE = "Cheque"
    FORMA_PAGO_DEPOSITO = "Deposito"
    CHOICE_FORMAPAGO = ((FORMA_PAGO_EFECTIVO, "Efectivo"), (FORMA_PAGO_CHEQUE, "Cheque"), (FORMA_PAGO_DEPOSITO, "Deposito"),)

    forma_pago=models.CharField(max_length=10, choices= CHOICE_FORMAPAGO, default=FORMA_PAGO_EFECTIVO)
    referencia = models.CharField(max_length=100, default="")
    concepto = models.CharField(max_length=100)
    monto = models.DecimalField(max_digits=15, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    interes = models.DecimalField(max_digits=15, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    fecha_pago= models.DateField(verbose_name="Fecha de de pago")
    observacion= models.TextField()
    cuenta_cobrar = models.ForeignKey('CuentaCobrar', on_delete=models.CASCADE, related_name='abonos')

    def __str__(self):
        return "{0} {1} {2}".format(self.fecha_pago, self.monto, self.interes)



class Comentario(models.Model):
    fecha_creacion= models.DateTimeField(auto_now=True, verbose_name="Fecha de creacion")
    concepto = models.CharField(max_length=100)
    detalle= models.CharField(max_length=255)

    cuenta_cobrar = models.ForeignKey('CuentaCobrar', on_delete=models.CASCADE, related_name='comentarios')

    class Meta:
        verbose_name="Providencia"
        verbose_name_plural = "Providencias"
    def __str__(self):
        return "{0} {1}".format(self.fecha_creacion, self.concepto)

class TasaInteres(models.Model):
    tasa=models.DecimalField(max_digits=4, decimal_places=2, validators=[MinValueValidator(Decimal('0.00')), MaxValueValidator(Decimal('100'))])
    anio = models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(Decimal('2200'))])
    mes = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(Decimal('12'))])

    class Meta:
        verbose_name = "Tasa de Interes"
        verbose_name_plural = "Tasas de Interes"
        unique_together=['anio','mes']
        ordering = ['-anio','-mes']
    def __str__(self):
        return "{0} - {1}".format(calendar.month_name[self.mes],self.anio)



class InteresMensual(models.Model):
    fecha_inicio = models.DateField(null=True, blank=True, verbose_name="Fecha de inicio")
    fecha_fin = models.DateField(null=True, blank=True, verbose_name="Fecha de inicio")
    valor=models.DecimalField(max_digits=15, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    pagado = models.BooleanField(default=False)
    tasa = models.ForeignKey('TasaInteres', null=False, blank=False, on_delete=models.CASCADE, related_name='interesesmensuales')
    cuenta_cobrar = models.ForeignKey('CuentaCobrar', null=False, blank=False, on_delete=models.CASCADE, related_name='interesesmensuales')

    class Meta:
        verbose_name = "Interes mensual"
        verbose_name_plural = "Intereses mensuales"
        ordering = ['fecha_inicio']
    def __str__(self):
        return str(self.valor)

    def clean(self):
        #Interes.objects.filter()
        pass

app/tesoreria/forms.py
from django import forms
from app.tesoreria.models import CuentaCobrar, Comentario, Abono, TasaInteres, InteresMensual


class CuentaCobrarForm(forms.ModelForm):
    numero_titulo = forms.CharField(required=False)
    tipo_documento = forms.CharField(required=False)
    titulo = forms.CharField(required=False)
    class Meta:
        model = CuentaCobrar
        fields = '__all__'


class ComentarioForm(forms.ModelForm):
    detalle = forms.CharField(required=False)
    class Meta:
        model = Comentario
        fields = '__all__'


class AbonoForm(forms.ModelForm):
    observacion = forms.CharField(required=False)
    referencia = forms.CharField(required=False)
    class Meta:
        model = Abono
        fields = '__all__'

class TasaInteresForm(forms.ModelForm):
    class Meta:
        model = TasaInteres
        fields = '__all__'

class InteresMensualForm(forms.ModelForm):
    class Meta:
        model = InteresMensual
        fields = '__all__'

app/tesoreria/templates/tesoreria/abono/fragmento_lista.html
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Concepto</th>
            <th>Fecha de pago</th>
            <th>Monto</th>
            <th>Interes</th>
            <th>Referencia</th>
            <th>Acción</th>
        </tr>
        </thead>
        <tbody>
        {% for abono in abonos %}
        <tr>
            <td>
                {{ abono.concepto }}

            </td>
            <td>{{ abono.fecha_pago|default:"" }}</td>
            <td>{{ abono.monto }}</td>
            <td>{{ abono.interes }}</td>
            <td>{{ abono.referencia }}</td>
            <td>
                <a title="Eliminar"
                   {% if perms.tesoreria.delete_abono %}
                   class="btn btn-outline-danger"
                   onclick="return confirm('¿Está seguro de eliminar el registro?')"
                   href="{% url 'tesoreria:abono_eliminar' abono.id %}"
                   {% else %}
                   class="btn btn-outline-danger disabled"
                   {% endif %}>
                    <i class="fa fa-trash-o"></i>
                </a>
                <a title="Imprimir"
                   {% if perms.tesoreria.view_abono %}
                   class="btn btn-outline-info"
                   href="{% url 'tesoreria:abono_imprimir' abono.id %}"
                   {% else %}
                   class="btn btn-outline-danger disabled"
                   {% endif %}>
                    <i class="fa fa-file-pdf-o"></i>
                </a>
            </td>

        </tr>
        {% endfor %}
        </tbody>

    </table>
</div>

app/tesoreria/templates/tesoreria/abono/modal_agregar.html
<div class="modal fade" id="modal-abono-guardar">
    <form action="{% url 'tesoreria:abono_guardar' %}" method="POST" role="form" id="formAbono">
        {% csrf_token %}
        <input type="hidden" id="id" name="id" value="{{ abono.id }}"/>
        <input type="hidden" id="id_cuenta" name="cuenta_cobrar"  value="{{ cuenta_cobrar.id }}"/>
        <input type="hidden" name="next" value="{{ request.path }}"/>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{{ 'tesoreria.Abono'|verbose_name|capfirst  }}</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                         <div class="form-group col-md-12">
                            <label for="concepto">Concepto:</label>
                            <input type="text"
                                   class="form-control letras_man_min"
                                   placeholder="Concepto.."
                                   id="concepto"
                                   name="concepto"
                                   value="{{ abono.concepto }}"
                                   minlength="3"
                                   maxlength="255"
                                   required>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group">
                                <label for="forma_pago">Forma de pago:</label>
                                <select id="forma_pago" name="forma_pago" class="form-control" required>
                                    <option value="" selected="selected">-- Seleccione --</option>
                                    {% for key, value in CHOICE_FORMAPAGO %}
                                        <option value="{{ key }}"
                                                {% if abono.forma_pago == key %}selected{% endif %}>
                                            {{ value }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group col-md-6">
                            <label id="labelreferencia" for="referencia">Referencia:</label>
                            <input type="text"
                                   class="form-control letras_man_min"
                                   placeholder="Referencia.."
                                   id="referencia"
                                   name="referencia"
                                   value="{{ abono.referencia }}"
                                   minlength="3"
                                   maxlength="50">
                        </div>

                        <div class="form-group col-md-4">
                            <label for="monto">Monto:</label>
                            <input type="number"
                                   class="form-control monto"
                                   id="monto"
                                   name="monto"
                                   value="{{ abono.monto }}"
                                   min="0"
                                   max= "{{ cuenta_cobrar.saldo|add:cuenta_cobrar.interes }}"
                                   step="0.01"
                                   required>

                        </div>

                          {% now "Y-m-d" as ahora %}
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="form-group">
                                <label for="fecha_pago">Fecha de pago:</label>
                                <input type="date"
                                       class="form-control"
                                       placeholder="Fecha de pago.."
                                       name="fecha_pago"
                                       id="fecha_pago"
                                       min="{{ cuenta_cobrar.fecha_emision | date:'Y-m-d'|default:ahora  }}"
                                      max="{{ abono.fecha_pago|date:'Y-m-d'|default:ahora }}"
                                       value="{{ abono.fecha_pago|date:'Y-m-d'|default:ahora }}"
                                       required>
                            </div>

                        </div>
                         <div class="form-group col-md-4">
                                <label for="deuda">Deuda a la fecha:</label>
                                <input type="text"
                                       class="form-control"
                                       placeholder="Deuda a la fecha"
                                       id="deuda"
                                       name="deuda"
                                       value="{{ cuenta_cobrar.saldo|add:cuenta_cobrar.interes }}"
                                       disabled
                                       required>
                        </div>

                        <div class="form-group col-md-6">
                            <input type="hidden"
                                   class="form-control"
                                   id="interes"
                                   name="interes"
                                   value="{{ abono.interes }}"
                                   minlength="0"
                                   maxlength="10"
                                   required>
                        </div>


                        <div class="form-group col-md-12">
                            <label for="observacion">Observación:</label>
                            <input type="text"
                                   class="form-control letras_man_min"
                                   placeholder="Observación.."
                                   id="observacion"
                                   name="observacion"
                                   value="{{ abono.observacion }}"
                                   minlength="3"
                                   maxlength="255"
                                   required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-ban"></i>Cancelar
                    </button>
                    <button id="enviar" type="submit" class="btn btn-primary"><i class="fa fa-save"></i>Registrar</button>
                </div>
            </div>
        </div>
    </form>
</div>