api/core/urls.py
from django.conf.urls import url

from api.core import views

urlpatterns = [
    url(r'^catalogo-item-por-codigo$', views.catalogo_item_por_codigo),
    url(r'^catalogo-item-lista-por-catalogo$', views.catalogo_item_lista_por_catalogo),
    url(r'^canton-lista-por-provincia$', views.canton_lista_por_provincia),
    url(r'^pais-lista$', views.pais_lista),
    url(r'^provincia-lista-por-pais$', views.provincia_lista_por_pais),
    url(r'^parroquia-lista-por-canton$', views.parroquia_lista_por_canton),
    url(r'^parroquia-lista$', views.parroquia_lista),
    url(r'^persona-o-registrocivil$', views.persona_o_registrocivil),
    url(r'^persona-lista-paginacion$', views.persona_lista_paginacion),
    url(r'^persona-lista-direcciones$', views.persona_lista_direcciones),
]

app/core/urls.py
from django.conf.urls import url

from app.core.utils import validador
from . import views
app_name = 'core'
urlpatterns = [
    url(r'^direccion/crear/(?P<persona_id>[\d]+)$', views.direccion_crear, name='direccion_crear'),
    url(r'^direccion/editar/(?P<id>[\d]+)$', views.direccion_editar, name='direccion_editar'),
    url(r'^direccion/eliminar/(?P<id>[\d]+)$', views.direccion_eliminar, name='direccion_eliminar'),
    url(r'^direccion/guardar/(?P<persona_id>[\d]+)$', views.direccion_guardar, name='direccion_guardar'),
    #agregados
    url(r'^direccion/crear_momentaneo/(?P<persona_id>[\d]+)$', views.direccion_crear_momentaneo, name='direccion_crear_momentaneo'),
    url(r'^direccion/editar_momentaneo/(?P<id>[\d]+)$', views.direccion_editar_momentaneo, name='direccion_editar_momentaneo'),
    url(r'^direccion/guardar_momentaneo/(?P<persona_id>[\d]+)$', views.direccion_guardar_momentaneo, name='direccion_guardar_momentaneo'),
    url(r'^direccion/basico_guardar/(?P<persona_id>[\d]+)$', views.direccion_basico_guardar, name='direccion_basico_guardar'),
    url(r'^direccion/basico_detalle/(?P<id>[\d]+)$', views.direccion_basico_detalle, name='direccion_basico_detalle'),

    url(r'^persona/editar/(?P<id>[\d]+)$', views.persona_editar, name='persona_editar'),
    url(r'^persona/guardar$', views.persona_guardar, name='persona_guardar'),
    ##agregados

    url(r'^persona/crear_basico/(?P<cedula>[\d]+)', views.persona_basico_registro, name='persona_basico_registro'),
    url(r'^persona/editar_momentaneo/(?P<id>[\d]+)$', views.persona_editar_momentaneo, name='persona_editar_momentaneo'),
    url(r'^persona/guardar_nuevo$', views.persona_guardar_momentaneo, name='persona_guardar_momentaneo'),
    url(r'^persona/listar_momentaneo/', views.persona_listar_momentaneo, name='persona_listar_momentaneo'),
    url(r'^persona/guardar_momentaneo$', views.persona_guardar_momentaneo_adm, name='persona_guardar_momentaneo_adm'),
    url(r'^persona/basico_guardar$', views.persona_basico_guardar, name='persona_basico_guardar'),

    url(r'^relacion/buscar/(?P<persona_id>[\d]+)$', views.relacion_buscar, name='relacion_buscar'),
    url(r'^relacion/crear/(?P<persona_id>[\d]+)$', views.relacion_crear, name='relacion_crear'),
    url(r'^relacion/editar/(?P<id>[\d]+)$', views.relacion_editar, name='relacion_editar'),
    url(r'^relacion/eliminar/(?P<id>[\d]+)$', views.relacion_eliminar, name='relacion_eliminar'),
    url(r'^relacion/guardar/(?P<persona_id>[\d]+)$', views.relacion_guardar, name='relacion_guardar'),

    url(r'^validar/campo-unico/', validador.validar_campo_unico, name='validar_campo_unico'),
    url(r'^validar/numero-documento/', validador.validar_numero_documento, name='validar_numero_documento'),
]

siaa/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from siaa import views

urlpatterns = [
    path('', views.index, name='index'),
    path(r'admin/', admin.site.urls),
    path('autenticacion/', include('app.autenticacion.urls')),
    path('academico/', include('app.academico.urls')),
    path('cientifica/', include('app.cientifica.urls')),
    path('core/', include('app.core.urls')),
    path('hveterinario/', include('app.hveterinario.urls')),
    path('reporte/', include('app.reporte.urls')),
    path('organico/', include('app.organico.urls')),
    path('planificacion/', include('app.planificacion.urls')),
    path('seguridad/', include('app.seguridad.urls')),
    path('seguridad-informacion/', include('app.seguridad_informacion.urls')),
    path('talento-humano/', include('app.talento_humano.urls')),
    path('tesoreria/', include('app.tesoreria.urls')),

    # Url de api
    path('api/v1/bienes/', include('api.bienes.urls')),
    path('api/v1/configuracion/', include('api.configuracion.urls')),
    path('api/v1/core/', include('api.core.urls')),
    path('api/v1/curricular/', include('api.curricular.urls' )),
    path('api/v1/organico/', include('api.organico.urls')),
    path('api/v1/recaudacion/', include('api.recaudacion.urls')),
    path('api/v1/seguridad/', include('api.seguridad.urls')),
    path('api/v1/talento-humano/', include('api.talento_humano.urls')),

    #Url servicios externos
    path('api/v1/bsg/', include(('api.bsg.urls', 'api_bsg'))),
    path('api/v1/banco/', include(('api.banco.urls', 'api_banco'))),
    path('api/v1/eventos/', include(('api.eventos.urls', 'api_eventos'))),
    path('api/v1/google/', include(('api.google.urls', 'api_google'))),
    path('api/v1/ldap/', include(('api.ldap.urls', 'api_ldap'))),
    path('api/v1/sga/', include(('api.sga.urls', 'api_sga'))),
]

api/core/views.py
import requests
from rest_framework import status
from rest_framework.decorators import renderer_classes, api_view
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response

from api.core.serializers import *
from app.configuracion.models import DetalleParametrizacion
from app.core.models import *
from app.core.utils.general import api_paginacion

@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def catalogo_item_por_codigo(request):
    """
    Permite obtener un catálogo item en base a su codigo(unico)
    :param request:
    :return:
    """
    try:
        codigo = request.query_params['codigo']
        catalogoItem = CatalogoItem.objects.filter(activo=True, codigo_th=codigo).first()
        serializer = CatalogoItemSerializer(catalogoItem)
        return Response({'status': status.HTTP_200_OK,
                         'data': serializer.data,
                         'message': ''})
    except Exception as e:
        return Response({
            'status': status.HTTP_500_INTERNAL_SERVER_ERROR,
            'message': 'Error en el servicio'
        }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def catalogo_item_lista_por_catalogo(request):
    """
    Obtiene los catalogos items por el codigo del catalogo padre
    :param request:
    :return:
    """
    try:
        codigo_catalogo = request.query_params['codigoCatalogo']
        catalogo_items = CatalogoItem.objects.filter(activo=True,
                                                     catalogo__codigo=codigo_catalogo).order_by('orden')
        serializer = CatalogoItemRecursivoSerializer(catalogo_items, many=True)
        return Response({'status': status.HTTP_200_OK,
                         'data': serializer.data,
                         'message': ''})
    except Exception as e:
        return Response({
            'status': status.HTTP_500_INTERNAL_SERVER_ERROR,
            'message': 'Error en el servicio'
        }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def canton_lista_por_provincia(request):
    """
    Retorna todas las cantones de una provincia, estado de la petición y mensaje.
    :param request:
    :return:
    """
    cantones = Canton.objects.filter(provincia__id=request.query_params['provincia_id'])
    serializer = CantonSerializer(cantones, many=True)
    return Response({'status': status.HTTP_200_OK,
                     'data': serializer.data})


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def pais_lista(request):
    """
    Retorna todas los paises, estado de la petición y mensaje.
    :param request:
    :return:
    """
    try:
        queryset = Pais.objects.all()
        serializer = PaisSerializer(queryset, many=True)
        return Response({'status': status.HTTP_200_OK,
                         'data': serializer.data})
    except Exception as e:
        return Response({'status': status.HTTP_500_INTERNAL_SERVER_ERROR,
                         'message': 'Error en el servicio'},
                        status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def provincia_lista_por_pais(request):
    """
    Retorna todas las provincias de un pais, estado de la petición y mensaje.
    :param request:
    :return:
    """
    provincias = Provincia.objects.filter(pais__id=request.query_params['pais_id'])
    serializer = ProvinciaSerializer(provincias, many=True)
    return Response({'status': status.HTTP_200_OK,
                     'data': serializer.data})


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def parroquia_lista_por_canton(request):
    """
    Retorna todas las parroquias de una canton, estado de la petición y mensaje.
    :param request:
    :return:
    """
    parroquias = Parroquia.objects.filter(canton__id=request.query_params['canton_id'])
    serializer = ParroquiaSerializer(parroquias, many=True)
    return Response({'status': status.HTTP_200_OK,
                     'data': serializer.data})

@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def parroquia_lista(request):
    """
    Retorna todas las parroquias con la información de canton, provincia y pais, estado de la petición y mensaje.
    :param request:
    :return:
    """
    parroquias = Parroquia.objects.all().values('id', 'nombre', 'canton__nombre', 'canton__provincia__nombre', 'canton__provincia__pais__nombre')
    return Response({'status': status.HTTP_200_OK,
                     'data': parroquias})

@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def persona_o_registrocivil(request):
    """
    Retorna la persona si existe o retorna los datos del registro civil segun el número de identificación
    :param request:
    :return:
    """
    try:
        numero_documento = request.query_params['numero_documento']
        persona = Persona.objects.filter(numero_documento=numero_documento).first()

        # Existe la persona en el Siaaf
        if persona is not None:
            return Response({'data': PersonaSerializer(persona).data,
                             'status': status.HTTP_200_OK,
                             'message': None})
        # Persona es None, lo busca en el registro civil
        else:
            headers = {'content-type': "application/x-www-form-urlencoded", 'cache-control': "no-cache",
                       "charset": "utf-8"}
            url_siaaf = DetalleParametrizacion.get_detalle_parametrizacion('SIAAF', 'SIAAF_URL_PRODUCCION')
            url_bsg = '%s/api/v1/bsg/consultar-cedula/%s?force=False' % (
            url_siaaf.valor, numero_documento)
            response = requests.request("GET", url_bsg, headers=headers)

            if response.status_code == 200:
                data = response.json()['data']
                if data and data.get('CodigoError') == '000':
                    persona = Persona()
                    primer_apellido, segundo_apellido, primer_nombre, segundo_nombre = dividir_nombres_completos(data.get('Nombre'))
                    persona.primer_nombre = primer_nombre
                    persona.segundo_nombre = segundo_nombre
                    persona.primer_apellido = primer_apellido
                    persona.segundo_apellido = segundo_apellido
                    persona.numero_documento = data.get('NUI')
                    persona.profesion = data.get('Profesion', None)
                    persona.fecha_nacimiento = datetime.datetime.strptime(data.get('FechaNacimiento'),
                                                                             '%d/%m/%Y').date()
                    persona.tipo_documento = CatalogoItem.get_catalogo_item('TIPO_DOCUMENTO', 1)
                    persona.sexo = CatalogoItem.get_catalogo_item('TIPO_SEXO',
                                                                  0 if data.get('Sexo', None) == 'MUJER' else 1)

                    personaSerializer = PersonaSerializer(persona).data
                    personaSerializer['Calle'] = data.get('Calle', None)
                    personaSerializer['NumeroCasa'] = data.get('NumeroCasa', None)

                    return Response({'data': personaSerializer,
                                     'status': status.HTTP_200_OK,
                                     'message': None})

                else:
                    message = data.get('Error', 'Persona no encontrada')
            else:
                message = "Error al consultar del registro civil"

            return Response({'data': None,
                             'status': status.HTTP_200_OK,
                             'message': message})
    except:
        return Response({'data': None,
                         'status': status.HTTP_500_INTERNAL_SERVER_ERROR,
                         'message': None})

@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def persona_lista_paginacion(request):
    """
    Retorna un diccionario con la lista de personas segun la
    paginación, estado de la petición y un mensaje
    :param request:
    :return:
    """
    try:
        filter = request.query_params['filter']
        page = request.query_params['page']
        numero_items_por_pagina = request.query_params['numberItems']
        queryset = Persona.objects.all()
        if filter:
            queryset = Persona.buscar(filter)
        personas = api_paginacion(queryset, page, numero_items_por_pagina)
        serializer = PersonaSerializer(personas, many=True)
        return Response({'status': status.HTTP_200_OK,
                         'data': serializer.data,
                         'message': '',
                         'count': queryset.count()})
    except Exception as e:
        return Response({
            'status': status.HTTP_500_INTERNAL_SERVER_ERROR,
            'message': 'Error en el servicio'
        }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def persona_lista_direcciones(request):
    """
    Retorna la lista de direcciones asociados al id de la persona.
    :param request:
    :return:
    """
    direcciones = Direccion.objects.filter(persona__id=request.query_params['persona_id']).all()
    return Response({'data': DireccionSerializer(direcciones, many=True).data,
                     'status': status.HTTP_200_OK,
                     'message': None})

app/core/templates/core/relacion/editar.html
{% extends 'layout.html' %}

{% block titulo %}
    Crear relación
{% endblock %}

{% block migas %}
     {% include 'navegacion.html' with navegacion=navegacion %}
{% endblock %}

{% block contenido %}
    <div class="card card-box">
        <div class="card-head">
            <header>Buscar persona</header>
        </div>
        <div class="card-body ">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <form action="{% url 'core:relacion_buscar' persona.id %}" class="form-inline" method="POST"
                          name="form-buscar">
                        {% csrf_token %}
                        <div class=" m-r-20">
                            Buscar por cédula:
                        </div>
                        <div class=" m-r-20">
                            <input type="hidden" name="next" value="{{ next }}">
                            {{ persona_buscar_form.criterio }}
                        </div>
                        <div>
                            <button type='submit' class='btn btn-primary btn-sm'>
                                <i class="fa fa-save"></i> Buscar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="card card-box">
        <div class="card-head">
            <header>Datos de relacion familiar</header>
        </div>
        <div class="card-body ">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <form action="{% url 'core:relacion_guardar' persona.id %}" class="form-horizontal auto-validate" method="POST" name="form-crear">
                        {% csrf_token %}
                        <table class="table table-hover">
                            <input type="hidden" name="next" value="{{ next }}">
                            <input type="hidden" name="id" value="{{ relacion.id }}"/>
                            {{ relacion_form }}
                        </table>
                        <div class="text-center">
                            <button type='submit' class='btn btn-primary m-r-20'>
                                <i class="fa fa-save"></i> Guardar
                            </button>
                            <a class='btn btn-default' href="{{ next }}#tab_relacion">
                                <i class="fa fa-ban"></i> Cancelar
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

app/core/templates/core/relacion/fragmento_lista.html
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    {% if usuario.estudiante %}
    {% include 'info_mensaje.html' with title="Estimado Usuario" text="Por favor ingrese obligatoriamente los  datos de su PADRE O MADRE (al menos uno de los dos)" %}
    {% else %}
    {% include 'info_mensaje.html' with title="Estimado Usuario" text="Por favor ingrese al menos un familiar  obligatoriamente, hijos (si existe), cónyuge o conviviente (si existe); y marcar mínimo un Contacto (obligatorio  teléfono y celular)." %}
    {% endif %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Familiares y contactos
                <a href="{% url 'core:relacion_crear' persona.id %}?next={{request.path}}"
                   class="btn btn-info btn-circle btn-xs pull-right" role="button">
                    <i class="fa fa-plus-circle"></i>Nuevo</a>
            </h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Relación</th>
                        <th>Identificación</th>
                        <th>Nombres/Apellidos</th>
                        <th>Teléfono/Celular</th>
                        <th>Fecha de nacimiento</th>
                        <th>Nivel de instrucción</th>
                        <th>Contacto</th>
                        <th>Trabajo en UNL</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for relacion in persona.expediente.relacion_set.all %}
                    <tr>
                        <td>{{ relacion.tipo_relacion }}</td>
                        <td>{{ relacion.numero_documento }}</td>
                        <td>{{ relacion.nombres }} {{ relacion.apellidos}}</td>
                        <td>{{ relacion.telefono| default:"" }} {{ relacion.celular| default:"" }}</td>
                        <td>{{ relacion.fecha_nacimiento| default:"" }}</td>
                        <td>{{ relacion.nivel_instruccion| default:"" }}</td>
                        <td align="center">
                            {% if relacion.contacto %}
                            <span class="fa fa-check" aria-hidden="true"></span>
                            {% endif %}
                        </td>
                        <td align="center">
                            {% if relacion.nepotismo %}
                            <span class="fa fa-check" aria-hidden="true"></span>
                            {% endif %}
                        </td>
                        <td>
                            <a class="btn btn-outline-info"
                               title="Editar"
                               href="{% url 'core:relacion_editar' relacion.id %}?next={{request.path}}">
                                <i class="fa fa-edit"></i></a>
                            <a class="btn btn-outline-danger"
                               title="Eliminar"
                               onclick="return confirm('¿Está seguro de eliminar el registro?')"
                               href="{% url 'core:relacion_eliminar' relacion.id %}?next={{request.path}}">
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>